[package]
name = "waterfall"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive", "env"] }
elements = "0.24.1"
env_logger = "0.11.3"
hyper = { version = "1.2.0", features = ["full"] }
log = "0.4.21"
tokio = { version = "1.36.0", features = ["rt", "macros", "rt-multi-thread"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
hex = "0.4.3"
reqwest = "0.12.0"
